[window]
opacity = 0.7
blur = true
[colors.bright]
black = "0x888888"
blue = "0x289cd5"
cyan = "0x0a9b81"
green = "0x76b639"
magenta = "0xff2491"
red = "0xff0000"
white = "0xf8f8f8"
yellow = "0xe1a126"

[colors.normal]
black = "0x171717"
blue = "0x16b1fb"
cyan = "0x0fdcb6"
green = "0x97d01a"
magenta = "0xff2491"
red = "0xd81765"
white = "0xebebeb"
yellow = "0xffa800"

[colors.primary]
background = "0x000000" #"0x0B0C0F" #"0x000000"
foreground = "0xf8f8f8"

[font]
size = 9.5

[font.bold]
family = "ComicShannsMonoNerdFontPropo"
style = "Bold"

[font.bold_italic]
family = "ComicShannsMonoNerdFontPropo"
style = "Bold Italic"

[font.italic]
family = "ComicShannsMonoNerdFontPropo"
style = "Italic"

[font.normal]
family = "ComicShannsMonoNerdFontPropo"
style = "Bold"


   
